//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TI_xdt99_IDE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_Base {
            get {
                return ((string)(this["Xdt_Base"]));
            }
            set {
                this["Xdt_Base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Editor_Binary {
            get {
                return ((string)(this["Editor_Binary"]));
            }
            set {
                this["Editor_Binary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Editor_Options {
            get {
                return ((string)(this["Editor_Options"]));
            }
            set {
                this["Editor_Options"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_Projects {
            get {
                return ((string)(this["Xdt_Projects"]));
            }
            set {
                this["Xdt_Projects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_Library {
            get {
                return ((string)(this["Xdt_Library"]));
            }
            set {
                this["Xdt_Library"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_Assembler {
            get {
                return ((string)(this["Xdt_Assembler"]));
            }
            set {
                this["Xdt_Assembler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_AsOptions_Object {
            get {
                return ((string)(this["Xdt_AsOptions_Object"]));
            }
            set {
                this["Xdt_AsOptions_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_AsOptions_Rpk {
            get {
                return ((string)(this["Xdt_AsOptions_Rpk"]));
            }
            set {
                this["Xdt_AsOptions_Rpk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_AsOptions_Image {
            get {
                return ((string)(this["Xdt_AsOptions_Image"]));
            }
            set {
                this["Xdt_AsOptions_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_BasConv {
            get {
                return ((string)(this["Xdt_BasConv"]));
            }
            set {
                this["Xdt_BasConv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_BasConv_Load {
            get {
                return ((string)(this["Xdt_BasConv_Load"]));
            }
            set {
                this["Xdt_BasConv_Load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DiskManager {
            get {
                return ((string)(this["Xdt_DiskManager"]));
            }
            set {
                this["Xdt_DiskManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCreate_Diskfile {
            get {
                return ((string)(this["Xdt_DmCreate_Diskfile"]));
            }
            set {
                this["Xdt_DmCreate_Diskfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCopy_Source {
            get {
                return ((string)(this["Xdt_DmCopy_Source"]));
            }
            set {
                this["Xdt_DmCopy_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCopy_Object {
            get {
                return ((string)(this["Xdt_DmCopy_Object"]));
            }
            set {
                this["Xdt_DmCopy_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCopy_List {
            get {
                return ((string)(this["Xdt_DmCopy_List"]));
            }
            set {
                this["Xdt_DmCopy_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCopy_Image {
            get {
                return ((string)(this["Xdt_DmCopy_Image"]));
            }
            set {
                this["Xdt_DmCopy_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmCopy_Run {
            get {
                return ((string)(this["Xdt_DmCopy_Run"]));
            }
            set {
                this["Xdt_DmCopy_Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Xdt_DmShow_Directory {
            get {
                return ((string)(this["Xdt_DmShow_Directory"]));
            }
            set {
                this["Xdt_DmShow_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_Source {
            get {
                return ((string)(this["ExtWin_Source"]));
            }
            set {
                this["ExtWin_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_Object {
            get {
                return ((string)(this["ExtWin_Object"]));
            }
            set {
                this["ExtWin_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_List {
            get {
                return ((string)(this["ExtWin_List"]));
            }
            set {
                this["ExtWin_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_Rpk {
            get {
                return ((string)(this["ExtWin_Rpk"]));
            }
            set {
                this["ExtWin_Rpk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_Image {
            get {
                return ((string)(this["ExtWin_Image"]));
            }
            set {
                this["ExtWin_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_BasT {
            get {
                return ((string)(this["ExtWin_BasT"]));
            }
            set {
                this["ExtWin_BasT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_BasB {
            get {
                return ((string)(this["ExtWin_BasB"]));
            }
            set {
                this["ExtWin_BasB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtWin_Disk {
            get {
                return ((string)(this["ExtWin_Disk"]));
            }
            set {
                this["ExtWin_Disk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtEmu_Source {
            get {
                return ((string)(this["ExtEmu_Source"]));
            }
            set {
                this["ExtEmu_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtEmu_Object {
            get {
                return ((string)(this["ExtEmu_Object"]));
            }
            set {
                this["ExtEmu_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtEmu_List {
            get {
                return ((string)(this["ExtEmu_List"]));
            }
            set {
                this["ExtEmu_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtEmu_Image {
            get {
                return ((string)(this["ExtEmu_Image"]));
            }
            set {
                this["ExtEmu_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Load {
            get {
                return ((string)(this["Emu_Load"]));
            }
            set {
                this["Emu_Load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Machine {
            get {
                return ((string)(this["Emu_Machine"]));
            }
            set {
                this["Emu_Machine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_GromPort {
            get {
                return ((string)(this["Emu_GromPort"]));
            }
            set {
                this["Emu_GromPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_JoyPort {
            get {
                return ((string)(this["Emu_JoyPort"]));
            }
            set {
                this["Emu_JoyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_CS1 {
            get {
                return ((string)(this["Emu_CS1"]));
            }
            set {
                this["Emu_CS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_CS2 {
            get {
                return ((string)(this["Emu_CS2"]));
            }
            set {
                this["Emu_CS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_IoPort {
            get {
                return ((string)(this["Emu_IoPort"]));
            }
            set {
                this["Emu_IoPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb2 {
            get {
                return ((string)(this["Emu_Peb2"]));
            }
            set {
                this["Emu_Peb2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb3 {
            get {
                return ((string)(this["Emu_Peb3"]));
            }
            set {
                this["Emu_Peb3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb4 {
            get {
                return ((string)(this["Emu_Peb4"]));
            }
            set {
                this["Emu_Peb4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb5 {
            get {
                return ((string)(this["Emu_Peb5"]));
            }
            set {
                this["Emu_Peb5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb6 {
            get {
                return ((string)(this["Emu_Peb6"]));
            }
            set {
                this["Emu_Peb6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb7 {
            get {
                return ((string)(this["Emu_Peb7"]));
            }
            set {
                this["Emu_Peb7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Peb8 {
            get {
                return ((string)(this["Emu_Peb8"]));
            }
            set {
                this["Emu_Peb8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_FDD1 {
            get {
                return ((string)(this["Emu_FDD1"]));
            }
            set {
                this["Emu_FDD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_FDD2 {
            get {
                return ((string)(this["Emu_FDD2"]));
            }
            set {
                this["Emu_FDD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_FDD3 {
            get {
                return ((string)(this["Emu_FDD3"]));
            }
            set {
                this["Emu_FDD3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_FDD4 {
            get {
                return ((string)(this["Emu_FDD4"]));
            }
            set {
                this["Emu_FDD4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_HDD1 {
            get {
                return ((string)(this["Emu_HDD1"]));
            }
            set {
                this["Emu_HDD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_HDD2 {
            get {
                return ((string)(this["Emu_HDD2"]));
            }
            set {
                this["Emu_HDD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_HDD3 {
            get {
                return ((string)(this["Emu_HDD3"]));
            }
            set {
                this["Emu_HDD3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_DSK1 {
            get {
                return ((string)(this["Emu_DSK1"]));
            }
            set {
                this["Emu_DSK1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_DSK2 {
            get {
                return ((string)(this["Emu_DSK2"]));
            }
            set {
                this["Emu_DSK2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_DSK3 {
            get {
                return ((string)(this["Emu_DSK3"]));
            }
            set {
                this["Emu_DSK3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_DSK4 {
            get {
                return ((string)(this["Emu_DSK4"]));
            }
            set {
                this["Emu_DSK4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_WDS1 {
            get {
                return ((string)(this["Emu_WDS1"]));
            }
            set {
                this["Emu_WDS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_WDS2 {
            get {
                return ((string)(this["Emu_WDS2"]));
            }
            set {
                this["Emu_WDS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_WDS3 {
            get {
                return ((string)(this["Emu_WDS3"]));
            }
            set {
                this["Emu_WDS3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IDE_Project {
            get {
                return ((string)(this["IDE_Project"]));
            }
            set {
                this["IDE_Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IDE_Source {
            get {
                return ((string)(this["IDE_Source"]));
            }
            set {
                this["IDE_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Assembler_all {
            get {
                return ((bool)(this["IDE_chk_Assembler_all"]));
            }
            set {
                this["IDE_chk_Assembler_all"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Assembler_Object {
            get {
                return ((bool)(this["IDE_chk_Assembler_Object"]));
            }
            set {
                this["IDE_chk_Assembler_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Assembler_Rpk {
            get {
                return ((bool)(this["IDE_chk_Assembler_Rpk"]));
            }
            set {
                this["IDE_chk_Assembler_Rpk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Assembler_Image {
            get {
                return ((bool)(this["IDE_chk_Assembler_Image"]));
            }
            set {
                this["IDE_chk_Assembler_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_all {
            get {
                return ((bool)(this["IDE_chk_Copy_all"]));
            }
            set {
                this["IDE_chk_Copy_all"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_Source {
            get {
                return ((bool)(this["IDE_chk_Copy_Source"]));
            }
            set {
                this["IDE_chk_Copy_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_List {
            get {
                return ((bool)(this["IDE_chk_Copy_List"]));
            }
            set {
                this["IDE_chk_Copy_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_Object {
            get {
                return ((bool)(this["IDE_chk_Copy_Object"]));
            }
            set {
                this["IDE_chk_Copy_Object"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_Image {
            get {
                return ((bool)(this["IDE_chk_Copy_Image"]));
            }
            set {
                this["IDE_chk_Copy_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_Catalog {
            get {
                return ((bool)(this["IDE_chk_Copy_Catalog"]));
            }
            set {
                this["IDE_chk_Copy_Catalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_chk_Copy_AutoStart {
            get {
                return ((bool)(this["IDE_chk_Copy_AutoStart"]));
            }
            set {
                this["IDE_chk_Copy_AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_opt_Emu_EditAss {
            get {
                return ((bool)(this["IDE_opt_Emu_EditAss"]));
            }
            set {
                this["IDE_opt_Emu_EditAss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_opt_Emu_MiniMem {
            get {
                return ((bool)(this["IDE_opt_Emu_MiniMem"]));
            }
            set {
                this["IDE_opt_Emu_MiniMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_opt_Emu_ExBasic {
            get {
                return ((bool)(this["IDE_opt_Emu_ExBasic"]));
            }
            set {
                this["IDE_opt_Emu_ExBasic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Binary {
            get {
                return ((string)(this["Emu_Binary"]));
            }
            set {
                this["Emu_Binary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Path {
            get {
                return ((string)(this["Emu_Path"]));
            }
            set {
                this["Emu_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_RomPath {
            get {
                return ((string)(this["Emu_RomPath"]));
            }
            set {
                this["Emu_RomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_CartPath {
            get {
                return ((string)(this["Emu_CartPath"]));
            }
            set {
                this["Emu_CartPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_DiskPath {
            get {
                return ((string)(this["Emu_DiskPath"]));
            }
            set {
                this["Emu_DiskPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_HardPath {
            get {
                return ((string)(this["Emu_HardPath"]));
            }
            set {
                this["Emu_HardPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emu_Cart {
            get {
                return ((string)(this["Emu_Cart"]));
            }
            set {
                this["Emu_Cart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IDE_opt_Emu_other {
            get {
                return ((bool)(this["IDE_opt_Emu_other"]));
            }
            set {
                this["IDE_opt_Emu_other"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string Emu_Options {
            get {
                return ((string)(this["Emu_Options"]));
            }
            set {
                this["Emu_Options"] = value;
            }
        }
    }
}
